Classifying Iris Species Using Decision Trees

Dataset:
Iris Dataset

Preprocessing Steps:
Handle missing values if any.
Standardize features.
Encode categorical variables if any.

Task:
Implement a decision tree classifier to classify iris species and evaluate the model using confusion matrix and accuracy.



In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.datasets import load_iris

In [2]:
#loading dataset
iris = load_iris()
x = iris.data
y = iris.target

In [3]:
#preprocessing data
iris = pd.DataFrame(x).isnull().sum()
print(iris)

0    0
1    0
2    0
3    0
dtype: int64


In [5]:
#standardizing data
scaler = StandardScaler()
x = scaler.fit_transform(x)
print(x)

[[-9.00681170e-01  1.01900435e+00 -1.34022653e+00 -1.31544430e+00]
 [-1.14301691e+00 -1.31979479e-01 -1.34022653e+00 -1.31544430e+00]
 [-1.38535265e+00  3.28414053e-01 -1.39706395e+00 -1.31544430e+00]
 [-1.50652052e+00  9.82172869e-02 -1.28338910e+00 -1.31544430e+00]
 [-1.02184904e+00  1.24920112e+00 -1.34022653e+00 -1.31544430e+00]
 [-5.37177559e-01  1.93979142e+00 -1.16971425e+00 -1.05217993e+00]
 [-1.50652052e+00  7.88807586e-01 -1.34022653e+00 -1.18381211e+00]
 [-1.02184904e+00  7.88807586e-01 -1.28338910e+00 -1.31544430e+00]
 [-1.74885626e+00 -3.62176246e-01 -1.34022653e+00 -1.31544430e+00]
 [-1.14301691e+00  9.82172869e-02 -1.28338910e+00 -1.44707648e+00]
 [-5.37177559e-01  1.47939788e+00 -1.28338910e+00 -1.31544430e+00]
 [-1.26418478e+00  7.88807586e-01 -1.22655167e+00 -1.31544430e+00]
 [-1.26418478e+00 -1.31979479e-01 -1.34022653e+00 -1.44707648e+00]
 [-1.87002413e+00 -1.31979479e-01 -1.51073881e+00 -1.44707648e+00]
 [-5.25060772e-02  2.16998818e+00 -1.45390138e+00 -1.31544430e

In [12]:
#split data set
x_train, x_test, y_train, y_test =train_test_split(x,y,test_size=0.2,random_state=42)

In [13]:
#Model
model = DecisionTreeClassifier(random_state = 42)
model.fit(x_train,y_train)

DecisionTreeClassifier(random_state=42)

In [14]:
#evalute model
y_pred = model.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [15]:
#accuracy
accuracy = accuracy_score(y_test, y_pred)
print(accuracy)

1.0
